################################### Serbian language #####################################
[sr]
languageName = "Serbian (Latin)"
languageCode = "sr-Latn"
contentDir = "content/lat"
weight = 1
[sr.params]
########### footer content ##########
footer_menu_left = "Organizacija"
footer_menu_middle = ""
footer_menu_right = ""
copyright = "© 2025 Studentska organizacija Proton. Sva prava zadržana."
theme_by = "Tema preuzeta sa"


################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 2
[en.params]
########### footer content ##########
footer_menu_left = "Organization"
footer_menu_middle = ""
footer_menu_right = ""
copyright = "© 2025 Student organization Proton. All rights reserved."
theme_by = "Theme by"

