# main menu
[[main]]
name = "Početna"
url = "/"
weight = 1

[[main]]
name = "O nama"
url = "/about"
weight = 2

[[main]]
name = "Projekati"
url = "/projects"
weight = 3

[[main]]
name = "Galerija"
url = "/gallery"
weight = 4

[[main]]
name = "Kontakt"
url = "/contact"
weight = 5

# footer menu left
[[footer_left]]
name = "O nama"
url = "/about"
weight = 1

[[footer_left]]
name = "Projekti"
url = "/projects"
weight = 2

[[footer_left]]
name = "Galerija"
url = "/gallery"
weight = 3

[[footer_left]]
name = "Kontakt"
url = "/contact"
weight = 4
